# fruit
apiVersion: v1
kind: Service
metadata:
  name: fruit-svc
  namespace: prod
  labels:
    app: fruit
    env: prod
    lab: a205
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "custom-headers"}'
    #cloud.google.com/backend-config: '{"default": "custom-headers", "ports": {"80": "health-check"}}'
spec:
  type: NodePort
  selector:
    app: fruit
  ports:
  - name: fruit-http
    port: 80
    protocol: TCP
    targetPort: 80
