# custom headers
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: custom-headers
  namespace: prod
  labels:
    env: prod
    lab: a205
spec:
  customRequestHeaders:
    headers:
    - "X-CDN-Cache-ID:{cdn_cache_id}"
    - "X-CDN-Cache-Status:{cdn_cache_status}"
    - "X-Origin-Request-Header:{origin_request_header}"
    - "X-Client-RTT-msec:{client_rtt_msec}"
    - "X-Client-Region:{client_region}"
    - "X-Client-Region-Subdivision:{client_region_subdivision}"
    - "X-Client-City:{client_region},{client_city}"
    - "X-Client-City-Lat-Long:{client_city_lat_long}"
    - "X-TLS-SNI-Hostname:{tls_sni_hostname}"
    - "X-TLS-Version:{tls_version}"
    - "X-TLS-Cipher-Suite:{tls_cipher_suite}"
