apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: apps-02
  labels:
    lab: a205
spec:
  replicas: 1
  selector:
    matchLabels:
      run: client
  template:
    metadata:
      labels:
        run: client
    spec:
      containers:
      - image: debianx
        name: client
        command:
        - sh
        - -c
        - while true; do sleep 1; done
