apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-deploy
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - image: ${IMAGE_REPO}
        name: ${APP_NAME}
        ports:
        - containerPort: ${TARGET_PORT}
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-nlb
  namespace: ${NAMESPACE}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"${PORT}":{"name": "${NEG_NAME}"}}}'
  labels:
    app: ${APP_NAME}
spec:
  type: LoadBalancer
  ports:
  - nodePort:
    port: ${PORT}
    protocol: TCP
    targetPort: ${TARGET_PORT}
  selector:
    app: ${APP_NAME}
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-ilb
  namespace: ${NAMESPACE}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
  labels:
    app: ${APP_NAME}
spec:
  type: LoadBalancer
  ports:
  - nodePort:
    port: ${PORT}
    protocol: TCP
    targetPort: ${TARGET_PORT}
  selector:
    app: ${APP_NAME}
