apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-deploy
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - image: ${IMAGE_REPO}
        name: ${APP_NAME}
        ports:
        - protocol: TCP
          containerPort: ${TARGET_PORT}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-clusterip
  namespace: ${NAMESPACE}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"${PORT}":{"name": "${NEG_NAME}"}}}'
  labels:
    app: ${APP_NAME}
spec:
  ports:
  - name: ${SERVICE_NAME}
    protocol: TCP
    port: ${PORT}
    targetPort: ${TARGET_PORT}
  selector:
    app: ${APP_NAME}
  type: ClusterIP
